/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import sn.isi.dao.BD;
import sn.isi.dao.ClientImp;
import sn.isi.dao.IClient;
import sn.isi.entities.Client;

/**
 *
 * @author adji
 */
public class Liste extends javax.swing.JFrame {
    private DefaultTableModel model;
    /**
     * Creates new form LIiste
     */
    public Liste() {
        initComponents();
          this.model = new DefaultTableModel();
        this.model.addColumn("ID");
        this.model.addColumn("Prenom");
        this.model.addColumn("Nom");
        this.model.addColumn("EMAIL");
         this.model.addColumn("TELEPHONE");
            this.table.setModel(model);
                   IClient Iclient = new ClientImp();
        
         Client cli = new Client();
   
          BD db = new BD();
        try {
            db.open();

            List<Client> clients = Iclient.liste();
            for (Client client1 : clients) {
             
              this.model.addRow(new Object[]{client1.getId(),client1.getPrenom(),client1.getNom(),client1.getEmail(),client1.getTel()});
              
               
            }
            
        } catch (Exception ex) {
            Logger.getLogger(Formulaire.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listeP = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        retour = new javax.swing.JButton();
        retour1 = new javax.swing.JButton();
        retour2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listeP.setBackground(new java.awt.Color(35, 62, 88));

        table.setBackground(new java.awt.Color(35, 62, 88));
        table.setForeground(java.awt.Color.white);
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Prenom", "NOM", "EMAIL", "TELEPHONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setAutoscrolls(false);
        table.setGridColor(new java.awt.Color(35, 62, 88));
        jScrollPane1.setViewportView(table);

        retour.setText("RETOUR");
        retour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retourActionPerformed(evt);
            }
        });

        retour1.setText("RETOUR");
        retour1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout listePLayout = new javax.swing.GroupLayout(listeP);
        listeP.setLayout(listePLayout);
        listePLayout.setHorizontalGroup(
            listePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listePLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(listePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listePLayout.createSequentialGroup()
                    .addGap(193, 193, 193)
                    .addComponent(retour)
                    .addContainerGap(193, Short.MAX_VALUE)))
            .addGroup(listePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, listePLayout.createSequentialGroup()
                    .addContainerGap(203, Short.MAX_VALUE)
                    .addComponent(retour1)
                    .addGap(183, 183, 183)))
        );
        listePLayout.setVerticalGroup(
            listePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(listePLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(listePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listePLayout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addComponent(retour)
                    .addContainerGap(99, Short.MAX_VALUE)))
            .addGroup(listePLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(listePLayout.createSequentialGroup()
                    .addGap(247, 247, 247)
                    .addComponent(retour1)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );

        retour2.setText("RETOUR");
        retour2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retour2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(listeP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retour2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(listeP, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(retour2)
                .addGap(39, 39, 39))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void retourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retourActionPerformed
      
    }//GEN-LAST:event_retourActionPerformed

    private void retour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retour1ActionPerformed

    private void retour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retour2ActionPerformed
        // TODO add your handling code here:
          Accueil accueil = new Accueil();
        accueil.setVisible(true);
        dispose();
    }//GEN-LAST:event_retour2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Liste.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
     
                  
                new Liste().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel listeP;
    private javax.swing.JButton retour;
    private javax.swing.JButton retour1;
    private javax.swing.JButton retour2;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
